server:
  port: 80
  #  数据压缩
  compression:
    enabled: true
    min-response-size: 10
    excluded-user-agents: gozilla,traviata
    mime-types: application/json
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.two.train.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
          id-type: auto
          #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
          field-strategy: not_empty
  mapper-locations: classpath:/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql:///two_train?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: three
    password: team
logging:
  level:
    com.two.train: debug